### ISSUE TITLE
Port 8080 takes its sweet time to respond after npm run docker:up:daemon

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/docker-wordpress-starterkit#4]
We already kind of knew about this but there should be something in the docs (which I can add in) or, even better, some sort of terminal output during docker:up encouraging the user to be patient as the site comes up at http://localhost:8080.  In every instance, when I run that command, it takes Apache or PHP or maybe MariaDB at least a full minute to get going, and until that point port 8080 throws no response. 

It'd be great to come up with a graceful solution here, but I think first I want to figure out what's taking so long. Maybe @heygrady already knows, without any other information I'm suspecting Apache is doing something weird since we're not getting even an error page during this dead-zone.

**Comment by heygrady** [comment]
The start up script waits for MariaDB before launching Apache. It does this to ensure the database gets created properly. In practice this would only need done on initializing your WordPress site for the first time. But there's not a great way for the startup script to know that. It ends up not being too big of a deal becAuse MariaDB needs to be running for the site to work anyway.

It would be possible to output a message when the DB is ready. I'll look into that

**Comment by heygrady** [comment]
http://stackoverflow.com/a/34170214
